### ISSUE TITLE
iproute package missing from perfsonar-testpoint bundle for CentOS7

### ISSUE THREAD

**Issue by bltierney** [perfsonar/bundles#10]
iproute package missing from perfsonar-testbed bundle for CentOS7

**Comment by vvidic** [comment]
On Sat, May 13, 2017 at 10:17:05AM -0700, Brian Tierney wrote:
> iproute package missing from perfsonar-testbed bundle for CentOS7

Did you mean perfsonar-testpoint?  What error did you get?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by bltierney** [comment]
Yes, perfsonar-testpoint

error is /sbin/ip: command not found.

**Comment by vvidic** [comment]
On Mon, May 15, 2017 at 06:12:34AM -0700, Brian Tierney wrote:
> Yes, perfsonar-testpoint
> 
> error is /sbin/ip: command not found.

Ok, but you run this manually or it is needed by some library
or script?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by bltierney** [comment]
its called by both mesh_config and ls_registration_daemon.

**Comment by vvidic** [comment]
On Mon, May 15, 2017 at 06:30:12AM -0700, Brian Tierney wrote:
> its called by both mesh_config and ls_registration_daemon.

I think it could be a call from perl-shared:

./lib/perfSONAR_PS/Utils/Host.pm:    open( my $IP_ADDR, "-|", "/sbin/ip addr show" ) or return;

But it is strange that iproute is not in the base install
on CentOS7?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by bltierney** [comment]
I was surprised too, but its not in the based used by docker.

**Comment by vvidic** [comment]
On Mon, May 15, 2017 at 06:36:34AM -0700, Brian Tierney wrote:
> I was surprised too, but its not in the based used by docker. 

Ok, could be a docker thing than, but we can add it to
libperfsonar-perl just to be safe.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNet
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr
