### ISSUE TITLE
Add new psconfig packages to bundles

### ISSUE THREAD

**Issue by tonin** [perfsonar/bundles#12]
We probably want to add the new psconfig packages to the testpoint and/or centralmanagement bundle.

**Comment by vvidic** [comment]
Added in `debian/jessie`:
- `perfsonar-psconfig-maddash*` to `perfsonar-centralmanagement`
- `perfsonar-psconfig-pscheduler` to `perfsonar-testpoint`

**Comment by arlake228** [comment]
Just so you know, once I complete some more translation scripts, I plan to have the perfsonar-psconfig-pscheduler and perfsonar-psconfig-maddash packages obsolete the perfsonar-meshconfig-agent and perfsonar-meshconfig-guiagent packages respectively and automatically migrate over the configuration files of each. I'll be discussing this some more at the face-to-face on Wednesday afternoon.

**Comment by vvidic** [comment]
On Mon, Mar 05, 2018 at 06:24:11AM -0800, Andrew R. Lake wrote:
> Just so you know, once I complete some more translation scripts, I
> plan to have the perfsonar-psconfig-pscheduler and
> perfsonar-psconfig-maddash packages obsolete the
> perfsonar-meshconfig-agent and perfsonar-meshconfig-guiagent packages
> respectively and automatically migrate over the configuration files of
> each. I'll be discussing this some more at the face-to-face on
> Wednesday afternoon.

Ok, I guess there is no harm installing it in parallel for now so
we can test?

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by arlake228** [comment]
Correct, no harm in installing them in parallel. I am doing the same. Just make sure if you had a pointer to a JSON file in psconfig, you remove that file from meshconfig or else you'll get double tests.

**Comment by arlake228** [comment]
Whoops, hit wrong button
