### ISSUE TITLE
Remove dependency to bwctl

### ISSUE THREAD

**Issue by tonin** [perfsonar/bundles#14]
We need to decide if we want to just remove the dependency, also stop any running bwctl-server process or even add a conflict with the bwctl packages.

**Comment by arlake228** [comment]
References removed in master to the extent they can be in 4.1. If you do a grep, the ones that remain are mostly in RegularTesting. The Toolkit UI still uses this library for generating regular tests then converts it when it is done to psconfig. 

Tested locally in rpm with toolkit changes and seems to be working. Assigning to antoine to make sure they are merged in Debian.

**Comment by arlake228** [comment]
Removed and also added perfsonar-bwctl-compat package to RPM .spec file. Leaving open for Antoine to migrate to Debian.

**Comment by arlake228** [comment]
Is this done for Debian? If so we can close.

**Comment by vvidic** [comment]
Updated on the Debian side, closing.
