### ISSUE TITLE
perfsonar-testpoint installation not possible on Debian 11 Bullseye system

### ISSUE THREAD

**Issue by FS-Araali** [perfsonar/bundles#23]
I am running a Raspberry Pi 4 with the latest Pi OS / Debian 11 Bullseye, currently pefsonar-testpoint is available for Debain 10 Buster. Therefore, the installation fails due to package dependencies:

```
[root@RaspberryPiTeleoperation5G:/etc/apt/sources.list.d#](mailto:root@RaspberryPiTeleoperation5G:/etc/apt/sources.list.d#) apt-get install perfsonar-testpoint
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pscheduler-server : Depends: postgresql-11 but it is not installable or
                              postgresql-10 but it is not installable or
                              postgresql-9.6 but it is not installable or
                              postgresql-9.5 but it is not installable
                     Depends: postgresql-plpython3-11 but it is not installable or
                              postgresql-plpython3-10 but it is not installable or
                              postgresql-plpython3-9.6 but it is not installable or
                              postgresql-plpython3-9.5 but it is not installable
 python3-pscheduler : Depends: python3-pyjq
E: Unable to correct problems, you have held broken packages.
```

I was able to fix pscheduler-server : Depends: postgresql-11 etc. by modifying the source-list, to make the packages accessible on Debian 11 Bullseye:

```
deb [trusted=yes] http://security.debian.org/debian-security buster/updates main
deb [trusted=yes] http://ftp.de.debian.org/debian buster main
```

For python3-pscheduler : Depends: python3-pyjq, I was unfortunately not able to find any further information about this particular package and failed therefore to add it manually as workaround.

Do you know a possibility to solve this issue, or is there an alternative approach to get it running?

**Comment by tonin** [comment]
You are right, `python3-pyjq` is not available for Debian 11 yet and not available else where AFAIK.  We will provide this package through our usual repository when we'll be officially supporting that distro with some future versions of perfSONAR.

**Comment by mfeit-internet2** [comment]
Our version of PyJQ has a critical bug fix in it, so we have to build that anyway.   The [issue](https://github.com/doloopwhile/pyjq/issues/24) on this has been open for four years (with a link to my fix) and there hasn't been a lot of movement on it.

No matter, we'll get it built.

**Comment by FS-Araali** [comment]
Thanks for the feedback, I have found a solution that is sufficient for me at the moment. Nevertheless, I am pretty sure that I will look into the problem again at a later date.
Thank you, guys!
