### ISSUE TITLE
Moving bundle version tracking to NPToolkit/Config/Version.pm

### ISSUE THREAD

**Issue by tonin** [perfsonar/bundles#5]
The **ls-registration-daemon** is tracking both the toolkit version number, the bundle version number and the bundle type installed.  The toolkit version number is retrieved using the `get_version` sub from `Version.pm` but the bundle type and version are directly managed by the bundle packages writing directly to the `/etc/ls_registration_daemon.conf` file.

I think it would be better to have all this version tracking happening through a common API coming from the `Version.pm` module.  This would also make that information available for consumption from other part of the toolkit, like the web interface.

This needs refactoring in https://github.com/perfsonar/ls-registration-daemon and in https://github.com/perfsonar/perl-shared

**Comment by arlake228** [comment]
Fixed (see referenced commits)
