### ISSUE TITLE
Traceroute Viewer missing from perfSONAR-CentralManagement bundle

### ISSUE THREAD

**Issue by apertome** [perfsonar/bundles#7]
The way the bundles are created, the traceroute viewer is missing from the perfSONAR-CentralManagement bundle. As a result, the traceroute links appear when viewed through the maddash graphs, but the user gets a 404 error if the node doesn't have the Toolkit installed (it lives in /toolkit/gui/psTracerouteViewer/index.cgi).

It might be better to move this tool to the 'graphs' package, since the Toolkit depends on that anyway.

**Comment by arlake228** [comment]
I created a separate perfsonar-traceroute-viewer package and created a dependency on it in perfsonar-graphs. We should be good to go now.

**Comment by apertome** [comment]
Does the CentralManagement bundle also depend on it?

**Comment by arlake228** [comment]
Indirectly yes. CentralManagement depends on maddash which depends on perfsonar-graphs which depends on perfsonar-traceroute-viewer.
